Refactored Reference methods and upgraded to latest Firebase API
pkaminski/firecrypt pull request #6
Opened 2018-08-01 00:40 UTC by jwngr

* Created a new `FireCryptReference` class and moved it to its own file.
* Removed `firebase` as a dependency since the library now acts a HOC which does not directly rely on the Firebase SDK. It also now supports both the `firebase` and `firebase-admin` SDKs.
* Upgraded the API to be compatible with the latest Firebase API, including renaming certain methods to properties, changing the names of certain methods, and adding others.
* Removed all priority-related APIs.
* Fixed a handful of bugs introduced in earlier PRs which have finally been properly tested.

Other comments inline.

2018-08-01 00:47 UTC, jwngr reviewed
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/6)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @pkaminski)

___
*[src/firecrypt.js, line 8 at r1](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LImwPFbDHcvMb1d0aq9:-LImwPFbDHcvMb1d0aqA:b7it7rq) ([raw file](https://github.com/pkaminski/firecrypt/blob/3d0e89fff1a6067755497ab0651f9819852c8956/src/firecrypt.js#L8)):*
> ```JavaScript
>   require('cryptojs-extension/build_node/siv');
>   try {
>     require('firebase-childrenkeys');
> ```

I was not planning to add another implementation of `childrenKeys()` in this library. If you pass it a ref that defines `childrenKeys()`, it will properly use it.
___
*[src/firecrypt.js, line 56 at r1](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LImvpfYD1ppD3iZ3qgt:-LImvpfYD1ppD3iZ3qgu:b-e1r6z1) ([raw file](https://github.com/pkaminski/firecrypt/blob/2b0660d3c41e1dba8df41e8e9e6bdcb64326e7f3/src/firecrypt.js#L56)):*
> ```JavaScript
>       case 'aes-siv':
>         if (!options.key) throw new Error('You must specify a key to use AES encryption.');
>         this.encryptionKeyCheckValue = setupAesSiv(options.key, options.keyCheckValue);
> ```

Beyond the changes to initializing FireCrypt, this is one of the only main API changes. Instead of being returned from the constructor, this is not a properly of the returned object. We will need to update all calling code which utilizes this.
___
*[src/firecrypt.js, line 106 at r1](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LImw8_O91ojuDPEllDq:-LImw8_O91ojuDPEllDr:b-i1bkoq) ([raw file](https://github.com/pkaminski/firecrypt/blob/2b0660d3c41e1dba8df41e8e9e6bdcb64326e7f3/src/firecrypt.js#L106)):*
> ```JavaScript
> }
> 
> function setupAesSiv(key, checkValue) {
> ```

It looks like a lot is changing here, but I really only changed `var` to `const` and added the `setEncryptStringFunction()` / `setDecryptStringFunction()` functions.
___
*[src/FireCryptReference.js, line 126 at r1](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LImwdmM5tc3pODU9XAQ:-LImwdmM5tc3pODU9XAR:bunqo24) ([raw file](https://github.com/pkaminski/firecrypt/blob/2b0660d3c41e1dba8df41e8e9e6bdcb64326e7f3/src/FireCryptReference.js#L126)):*
> ```JavaScript
>   }
> 
>   _interceptPush() {
> ```

This is the main thing I re-implemented. The old code used to rely on `set()` to handle the encryption, but that didn't work after upgrading. I now call `set()` directly. Same idea, just a few more lines of code.


<!-- Sent from Reviewable.io -->

2018-08-01 00:51 UTC, jwngr reviewed
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/6)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @pkaminski)

*[a discussion](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LImxtOI9mkHlIikL7Ws:-LImxtOI9mkHlIikL7Wt:b-8z4q9m) (no related file):*
I have tested this locally with my own test runner with AES encryption enabled (not just passthrough encryption) and ensured that the data written to Firebase is properly encrypted and decrypted. I plan to test this on the actual Reviewable website / server locally later this week. The test runner is pretty messy and not really ready for prime time, which is why I didn't include it in this PR. Let me know if you'd like it to be included though.

---


<!-- Sent from Reviewable.io -->

2018-08-02 07:09 UTC, pkaminski requested changes
The dependency on `firebase` is a good way to enforce use with compatible versions, even if we end up sticking to the injection design.  Any chance there's some common ancestors of `firebase` and `firebase-admin` that we could depend on?

> Reviewed 10 of 14 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/6#-:-LItJTHQ9ctVyiDTjzW3:b9etaj8)* status: all files reviewed, 7 unresolved discussions (waiting on @jwngr)

___
*[src/crypto.js, line 11 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItKzYx44Ic18P_36k9:-LItKzYx44Ic18P_36kA:b-ulyns1) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/crypto.js#L11)):*
> ```JavaScript
> }
> 
> export function setEncryptStringFunction(encryptString) {
> ```

Since the encryption/decryption functions must always be paired, it would make sense to have a single setter for both.
___
*[src/firecrypt.js, line 56 at r1](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LImvpfYD1ppD3iZ3qgt:-LItMn-n64Sn-TyNbv7B:b-r1fbxd) ([raw file](https://github.com/pkaminski/firecrypt/blob/2b0660d3c41e1dba8df41e8e9e6bdcb64326e7f3/src/firecrypt.js#L56)):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

Beyond the changes to initializing FireCrypt, this is one of the only main API changes. Instead of being returned from the constructor, this is not a properly of the returned object. We will need to update all calling code which utilizes this.
</blockquote></details>

OK, though I suspect we'll end up with an explicit `initialize` method after all per the above.
___
*[src/firecrypt.js, line 18 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItLUQo8gX0dsOO--_7:-LItLUQp6zHhfjtZz5n9:b-dr87n9) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/firecrypt.js#L18)):*
> ```JavaScript
> 
> export default class FireCrypt {
>   constructor(db, options = {}, specification = {}) {
> ```

It's not necessarily apparent from the API, but `initializeEncryption` is actually called multiple times within a single session as the AES key becomes available/unavailable or changes.  This must be able to happen without invalidating previous held refs.  (Note that in the old code the `specification` was actually reparsed at each call to `initializeEncryption` as well, but that is not required and would actually be better if it only happened once.)
___
*[src/firecrypt.js, line 90 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItNYF-2Dnw85OaThsX:-LItNYF-2Dnw85OaThsY:b606i37) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/firecrypt.js#L90)):*
> ```JavaScript
>     const pathOrRefIsNonemptyString = typeof pathOrRef === 'string' && pathOrRef !== '';
>     const pathOrRefIsNonNullObject = typeof pathOrRef === 'object' && pathOrRef !== null;
>     const pathOrRefIsFirebaseRef =
> ```

I'm confused -- does this accept raw Firebase refs?  Those should never be allowed to escape.
___
*[src/FireCryptReference.js, line 10 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItR0VeDhoueaTbF16f:-LItQsTe8fzMNsTaidGf:b-d4cnda) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/FireCryptReference.js#L10)):*
> ```JavaScript
>     this._ref = ref;
> 
>     this._interceptPush();
> ```

Any reason to declare all the intercepting methods dynamically, rather than just declaring them directly on the class?  (Or patching them onto the prototype, for generic ones.)
___
*[src/FireCryptReference.js, line 23 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItRQ3eE9M2HxMgLcuk:-LItRQ3eE9M2HxMgLcul:b-pwp0wc) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/FireCryptReference.js#L23)):*
> ```JavaScript
>     this._interceptWrite('update', 0);
> 
>     if (ref.childrenKeys) {
> ```

This check isn't going to work, since Firecrypt wraps raw Firebase references, not NodeFire wrappers.  It now occurs to me that this must have been one of the reasons I didn't end up integrating `childrenKeys` into `NodeFire`, since its results need to be decrypted but NodeFire is in a layer above Firecrypt.  I'm not sure how to make this work now -- ideas?  The nuclear option would be to integrate NodeFire and Firecrypt but I'd like to keep that as a last resort.
___
*[src/FireCryptReference.js, line 141 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItPPaI597r-E7Azglp:-LItPPaI597r-E7Azglq:b-3gigbf) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/FireCryptReference.js#L141)):*
> ```JavaScript
> 
>       const decryptedPushedRef = new FireCryptReference(crypto.decryptRef(pushedRef));
>       decryptedPushedRef.then = pushedRef.then;
> ```

Will calling this correctly chain onto the `encryptedRef.set` promise above if this method is called with an argument?  It doesn't look like it to me, but maybe there's some dark magic at play...
___
*[src/FireCryptReference.js, line 204 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItQaVS4X4gvYhVnMzr:-LItQaVS4X4gvYhVnMzs:b-cyou8g) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/FireCryptReference.js#L204)):*
> ```JavaScript
>       };
>       if (args.length > 1) {
>         const originalOnComplete = args[1];
> ```

Oh, does the new SDK still support callback arguments?  I thought it went to 100% promises for some reason.


<!-- Sent from Reviewable.io -->

2018-08-04 23:57 UTC, jwngr reviewed
Unfortunately not. We could potentially use a solution like https://www.npmjs.com/package/codependency, although I've never tried that before myself. Unfortunately, neither `peerDepenencies` nor `optionalDependencies` really fit this situation well. Let me know what you'd like to do.

> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/6#-:-LJ6EdIk-OWY5BuPKt6c:bew0pv6)* status: 6 of 14 files reviewed, 7 unresolved discussions (waiting on @pkaminski and @jwngr)

___
*[src/crypto.js, line 11 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItKzYx44Ic18P_36k9:-LJ6EcV76dOzuuSgOzEO:b-896fix) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/crypto.js#L11)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Since the encryption/decryption functions must always be paired, it would make sense to have a single setter for both.
</blockquote></details>

Done.
___
*[src/firecrypt.js, line 56 at r1](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LImvpfYD1ppD3iZ3qgt:-LJ6JYso36OO5YMyGvcV:b-p7mlh9) ([raw file](https://github.com/pkaminski/firecrypt/blob/2b0660d3c41e1dba8df41e8e9e6bdcb64326e7f3/src/firecrypt.js#L56)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

OK, though I suspect we'll end up with an explicit `initialize` method after all per the above.
</blockquote></details>

See my note above. 
___
*[src/firecrypt.js, line 18 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItLUQo8gX0dsOO--_7:-LJ6Fb5_6bsq8jdKUd4D:b-3d2qph) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/firecrypt.js#L18)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

It's not necessarily apparent from the API, but `initializeEncryption` is actually called multiple times within a single session as the AES key becomes available/unavailable or changes.  This must be able to happen without invalidating previous held refs.  (Note that in the old code the `specification` was actually reparsed at each call to `initializeEncryption` as well, but that is not required and would actually be better if it only happened once.)
</blockquote></details>

It's a bit unclear what the intended behavior is. Do you want to be able to create multiple `FireCrypt` instances, each with their own unique encryption key or algorithm? If so, we will need to update `crypto.js` to not have global variables. My thought would be to make it a class and instantiate a new instance of it for each `FireCrypt` instance. Or do you want all instances to essentially update according to the latest call?  If so, this should be the existing behavior with my code, although that is mostly by happenstance and there may be more work needed to make sure it all behaves properly.
___
*[src/firecrypt.js, line 90 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItNYF-2Dnw85OaThsX:-LJ6Jo6F6QQfcIksJwgQ:b-kw0sfl) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/firecrypt.js#L90)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I'm confused -- does this accept raw Firebase refs?  Those should never be allowed to escape.
</blockquote></details>

I was just mimicking the original Firebase API. I'm not even sure if you personally would ever use one ref to instantiate another one. I always just use the string version of this API. I can either only allow strings or update this to be an `pathOrRef instanceof FireCryptReference` check.
___
*[src/FireCryptReference.js, line 10 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItR0VeDhoueaTbF16f:-LJ6KN4X3f9hWutuyy_l:bkrf8qj) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/FireCryptReference.js#L10)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Any reason to declare all the intercepting methods dynamically, rather than just declaring them directly on the class?  (Or patching them onto the prototype, for generic ones.)
</blockquote></details>

Not really. Was mainly just going with a similar method your existing code used. Happy to update them if you'd lie me to.
___
*[src/FireCryptReference.js, line 23 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItRQ3eE9M2HxMgLcuk:-LJ6KeME0bmEpZnZTYrM:b4lazrk) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/FireCryptReference.js#L23)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

This check isn't going to work, since Firecrypt wraps raw Firebase references, not NodeFire wrappers.  It now occurs to me that this must have been one of the reasons I didn't end up integrating `childrenKeys` into `NodeFire`, since its results need to be decrypted but NodeFire is in a layer above Firecrypt.  I'm not sure how to make this work now -- ideas?  The nuclear option would be to integrate NodeFire and Firecrypt but I'd like to keep that as a last resort.
</blockquote></details>

Ugh yeah, that's a very good point. I don't think we should integrate the two. We can either just duplicate the code (it's not that much code) or keep it as a separate node module upon which both of these libraries rely. My instinct is to keep it as a separate module.
___
*[src/FireCryptReference.js, line 141 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItPPaI597r-E7Azglp:-LJ6M7W_31Dgr9TgTa2m:b-gcblr1) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/FireCryptReference.js#L141)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Will calling this correctly chain onto the `encryptedRef.set` promise above if this method is called with an argument?  It doesn't look like it to me, but maybe there's some dark magic at play...
</blockquote></details>

Yup, this properly chains with or without an argument.
___
*[src/FireCryptReference.js, line 204 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItQaVS4X4gvYhVnMzr:-LJ6LhNzEi8XJvLSggd2:bltan6f) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/FireCryptReference.js#L204)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Oh, does the new SDK still support callback arguments?  I thought it went to 100% promises for some reason.
</blockquote></details>

Nope, it's a hybrid of both. The idea was to minimize churn for people.


<!-- Sent from Reviewable.io -->

2018-08-05 04:27 UTC, pkaminski requested changes
My reading of [`peerDependencies`](https://docs.npmjs.com/files/package.json#peerdependencies) implies that it should do the trick, at least as of `npm@3` and up.  Try adding both the server and client Firebase libraries as `peerDependencies` and see what happens, I guess?

> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/6#-:-LJ6uVlh6_HKHDnHaumS:b-lqq716)* status: all files reviewed, 5 unresolved discussions (waiting on @pkaminski)

___
*[src/firecrypt.js, line 18 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItLUQo8gX0dsOO--_7:-LJ7Fxtb5nHd6OGuuLtg:b-61d4i9) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/firecrypt.js#L18)):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

It's a bit unclear what the intended behavior is. Do you want to be able to create multiple `FireCrypt` instances, each with their own unique encryption key or algorithm? If so, we will need to update `crypto.js` to not have global variables. My thought would be to make it a class and instantiate a new instance of it for each `FireCrypt` instance. Or do you want all instances to essentially update according to the latest call?  If so, this should be the existing behavior with my code, although that is mostly by happenstance and there may be more work needed to make sure it all behaves properly.
</blockquote></details>

The old behavior was global but I think your proposal makes more sense:  encryption setup per `FireCrypt` instance, with `crypto.js` refactored into a class and nested inside.  This way, the client could set up encryption differently for different databases.  However, you'll now need to inject the crypto instance into every wrapper object -- that will be a pain...  Also, the encryption does need to be reconfigurable for each database.  Pulling together insights from the email thread I think we're looking at something like this:

```js
const appClass = admin || firebase.app.App.prototype;  // probe to pick the one that's loaded
const originalDb = appClass .database;
Object.defineProperty(appClass , 'database', {
  value: function(url) {return new FireCrypt(originalDb.call(this, url));}
});
const db = admin.database();  // or the firebase.app equivalent
const keyCheckValue = db.configureEncryption(options, specs);  // can be called multiple times
```

I'm not 100% sure about`firebase.app.App.prototype` above, you'll likely need to hack around a bit to see if it can be patched like that.  The `admin` will also need a safe `require` probe to be isomorphic.

If you can't pull off the monkey patching on the client SDK then I think the overall API still stands, it'll just be up to the client to call the `FireCrypt` constructor.
___
*[src/firecrypt.js, line 90 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItNYF-2Dnw85OaThsX:-LJ6v9h44X5UneW8wBhA:b-yvvyeb) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/firecrypt.js#L90)):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

I was just mimicking the original Firebase API. I'm not even sure if you personally would ever use one ref to instantiate another one. I always just use the string version of this API. I can either only allow strings or update this to be an `pathOrRef instanceof FireCryptReference` check.
</blockquote></details>

This should behave just like the underlying `ref()` method, but the [docs](https://firebase.google.com/docs/reference/js/firebase.database.Database#ref) seem to imply that it only accepts a path or `undefined` so I'm OK limiting it to those.

Do we also need a `refFromURL(url)` for compatibility?
___
*[src/FireCryptReference.js, line 10 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItR0VeDhoueaTbF16f:-LJ6w4o19Kbe5qs7DZKO:biqy8bh) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/FireCryptReference.js#L10)):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

Not really. Was mainly just going with a similar method your existing code used. Happy to update them if you'd lie me to.
</blockquote></details>

Yes, please do that.  The original code was patching them onto a prototype, which was both necessary and efficient.  With the delegation approach it's no longer necessary, and patching them onto each constructed instance is pretty inefficient.
___
*[src/FireCryptReference.js, line 23 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItRQ3eE9M2HxMgLcuk:-LJ7J8c51qOmdnmPG3GD:b-irin0q) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/FireCryptReference.js#L23)):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

Ugh yeah, that's a very good point. I don't think we should integrate the two. We can either just duplicate the code (it's not that much code) or keep it as a separate node module upon which both of these libraries rely. My instinct is to keep it as a separate module.
</blockquote></details>

Separate module sounds good but it doesn't solve the whole problem unless you monkeypatch it here.  Perhaps instead modify NodeFire to check if the underlying ref has a `childrenKeys` method and delegate to it, otherwise use the module?  Then here you could probe to see if the module is available, and if so define `FireCryptReference.prototype.childrenKeys` to delegate and decrypt, which would then get picked up by NodeFire rather than going directly to the module.

BTW, we may run into similar layering issues when you try to integrate permission denied debugging.
___
*[src/FireCryptReference.js, line 141 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItPPaI597r-E7Azglp:-LJ6wVSC3Fto_1JvOyHb:b-32g4ur) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/FireCryptReference.js#L141)):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

Yup, this properly chains with or without an argument.
</blockquote></details>

Can you explain how it works?  From what I can see, if an argument is provided then the promise returned by `pushedRef.set.apply(encryptedRef, args)` above gets thrown away.


<!-- Sent from Reviewable.io -->

2018-08-05 14:31 UTC, jwngr reviewed
Yeah, after giving `peerDependencies` a shot, I think it will work. It does throw the following pair of errors upon install, but they don't break the install and just alert that you need install another thing yourself:

```
$ npm i
npm WARN firecrypt@0.3.4 requires a peer of firebase@^5.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN firecrypt@0.3.4 requires a peer of firebase-admin@^5.13.1 but none is installed. You must install peer dependencies yourself.

added 65 packages from 87 contributors and audited 226 packages in 3.335s
found 0 vulnerabilities
```

There is no way to indicate that only one of them is required to be installed, but we can explain that in the documentation (which I still need to update).

> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/6#-:-LJ9MxW8ACGhTSjSHHi8:b-2fptev)* status: all files reviewed, 5 unresolved discussions (waiting on @jwngr and @pkaminski)

___
*[src/firecrypt.js, line 90 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItNYF-2Dnw85OaThsX:-LJ9OCRa7D1ur9O7uHh_:bxegust) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/firecrypt.js#L90)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

This should behave just like the underlying `ref()` method, but the [docs](https://firebase.google.com/docs/reference/js/firebase.database.Database#ref) seem to imply that it only accepts a path or `undefined` so I'm OK limiting it to those.

Do we also need a `refFromURL(url)` for compatibility?
</blockquote></details>

I swear that this used to accept `refOrPath`... Super strange. Regardless, I agree that just accepting a path or `undefined` will be all you need. I made that change and I also added `refFromURL()` event though I can't say I ever used it.
___
*[src/FireCryptReference.js, line 10 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItR0VeDhoueaTbF16f:-LJ9UUuX2ubQpYVaBOji:b-lfronp) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/FireCryptReference.js#L10)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Yes, please do that.  The original code was patching them onto a prototype, which was both necessary and efficient.  With the delegation approach it's no longer necessary, and patching them onto each constructed instance is pretty inefficient.
</blockquote></details>

Done. I also cleaned up similar code in the other classes. I kept the `_interceptQuery()` patching there given the number of methods, but I can change that as well if you'd like.


<!-- Sent from Reviewable.io -->

2018-08-05 15:55 UTC, jwngr reviewed
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/6)* status: 3 of 14 files reviewed, 5 unresolved discussions (waiting on @pkaminski and @jwngr)

___
*[src/FireCryptReference.js, line 141 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItPPaI597r-E7Azglp:-LJ9d9E42i-WkOZDjtSL:b-cc6g5a) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/FireCryptReference.js#L141)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Can you explain how it works?  From what I can see, if an argument is provided then the promise returned by `pushedRef.set.apply(encryptedRef, args)` above gets thrown away.
</blockquote></details>

I see what you are saying. You mean that it may not properly wait until the `set()` method is complete. In my testing, it seems to always work, but I do think there is a race condition. I honestly just spent an inordinate amount of time trying to get this to work properly and even tried reverting this to something similar to what you had initially (which proxies the encryption via `set()`), but I was unable to get it to work properly. I honestly have no idea how your initial code ever worked to be honest. If you have an idea of how to do this properly, please let me know.


<!-- Sent from Reviewable.io -->

2018-08-05 17:24 UTC, jwngr reviewed
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/6)* status: 1 of 14 files reviewed, 5 unresolved discussions (waiting on @pkaminski and @jwngr)

___
*[src/firecrypt.js, line 18 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItLUQo8gX0dsOO--_7:-LJA5CcpA-EpgM4fweo_:bj0qwpa) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/firecrypt.js#L18)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

The old behavior was global but I think your proposal makes more sense:  encryption setup per `FireCrypt` instance, with `crypto.js` refactored into a class and nested inside.  This way, the client could set up encryption differently for different databases.  However, you'll now need to inject the crypto instance into every wrapper object -- that will be a pain...  Also, the encryption does need to be reconfigurable for each database.  Pulling together insights from the email thread I think we're looking at something like this:

```js
const appClass = admin || firebase.app.App.prototype;  // probe to pick the one that's loaded
const originalDb = appClass .database;
Object.defineProperty(appClass , 'database', {
  value: function(url) {return new FireCrypt(originalDb.call(this, url));}
});
const db = admin.database();  // or the firebase.app equivalent
const keyCheckValue = db.configureEncryption(options, specs);  // can be called multiple times
```

I'm not 100% sure about`firebase.app.App.prototype` above, you'll likely need to hack around a bit to see if it can be patched like that.  The `admin` will also need a safe `require` probe to be isomorphic.

If you can't pull off the monkey patching on the client SDK then I think the overall API still stands, it'll just be up to the client to call the `FireCrypt` constructor.

</blockquote></details>

I updated `crypto.js` to be it's own `Crypto` class and fed that through the rest of the classes and have it working the same as it was before. To be honest, I'm a bit confused as to what you are trying to do with `firebase.app.App.prototype` above and I don't think passing a `URL` is the right thing since `admin` is already being initialized with a `databaseURL`. The way I have it implemented right now is like this:

```
const originalDb = admin.database;

Object.defineProperty(admin, 'database', {
  value: () => new FireCrypt(originalDb())
});

const db = admin.database();

let keyCheckValue = db.configureEncryption(options, specification);

// ... later on

keyCheckValue = db.configureEncryption(otherOptions, otherSpecification);
```

This currently just uses a single instance `FireCrypt` and allows you to reconfigure it multiple times, which I believe suits your use case. If you want to have multiple concurrent `FireCrypt` instances, you can do:

```
const otherDb = admin.database();
const otherKeyCheckValue = otherDb.configureEncryption(otherOptions, otherSpecification);
```

What do you think?


<!-- Sent from Reviewable.io -->

2018-08-05 17:24 UTC, jwngr reviewed
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/6)* status: 1 of 14 files reviewed, 5 unresolved discussions (waiting on @pkaminski and @jwngr)

___
*[src/FireCryptReference.js, line 23 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItRQ3eE9M2HxMgLcuk:-LJA6ZJiDzjGy59eJGRA:b-eb0za0) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/FireCryptReference.js#L23)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Separate module sounds good but it doesn't solve the whole problem unless you monkeypatch it here.  Perhaps instead modify NodeFire to check if the underlying ref has a `childrenKeys` method and delegate to it, otherwise use the module?  Then here you could probe to see if the module is available, and if so define `FireCryptReference.prototype.childrenKeys` to delegate and decrypt, which would then get picked up by NodeFire rather than going directly to the module.

BTW, we may run into similar layering issues when you try to integrate permission denied debugging.

</blockquote></details>

That plan sounds good. I'm waiting for you to grant me access to push to the `firebase-childrenkeys` repo and then I'll get this updated.


<!-- Sent from Reviewable.io -->

2018-08-06 04:34 UTC, pkaminski requested changes
> Reviewed 13 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/6)* status: all files reviewed, 8 unresolved discussions (waiting on @pkaminski and @jwngr)

___
*[src/crypto.js, line 108 at r4](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LJCUgKs3zdjqeYm8MMX:-LJCUgKs3zdjqeYm8MMY:b-w2rq5j) ([raw file](https://github.com/pkaminski/firecrypt/blob/27121b43934849985fb3bffd023296cdabb28079/src/crypto.js#L108)):*
> ```JavaScript
>   }
> 
>   transformValue(path, value, transform) {
> ```

Instead of binding `transform` to the crypto instance at all the call sites it probably makes more sense to bind it here, or even just accept `'encrypt' || 'decrypt'` as the parameter and look it up and bind it.  (The only reason I passed the raw functions originally is because it was convenient.)
___
*[src/firecrypt.js, line 18 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItLUQo8gX0dsOO--_7:-LJC5yUuAbt6vNlJFNdU:b-k79sbv) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/firecrypt.js#L18)):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

I updated `crypto.js` to be it's own `Crypto` class and fed that through the rest of the classes and have it working the same as it was before. To be honest, I'm a bit confused as to what you are trying to do with `firebase.app.App.prototype` above and I don't think passing a `URL` is the right thing since `admin` is already being initialized with a `databaseURL`. The way I have it implemented right now is like this:

```
const originalDb = admin.database;

Object.defineProperty(admin, 'database', {
  value: () => new FireCrypt(originalDb())
});

const db = admin.database();

let keyCheckValue = db.configureEncryption(options, specification);

// ... later on

keyCheckValue = db.configureEncryption(otherOptions, otherSpecification);
```

This currently just uses a single instance `FireCrypt` and allows you to reconfigure it multiple times, which I believe suits your use case. If you want to have multiple concurrent `FireCrypt` instances, you can do:

```
const otherDb = admin.database();
const otherKeyCheckValue = otherDb.configureEncryption(otherOptions, otherSpecification);
```

What do you think?
</blockquote></details>

I'm passing `url` since that's what the `database` method (optionally) [expects](https://firebase.google.com/docs/reference/admin/node/admin.app.App#database), and we need to remain API-compatible.

The `firebase.app.App.prototype` bit is to make Firecrypt compatible with the client SDK.  While `firebase-admin` has a static `admin.database()` method, the client SDK has it as an instance method on `firebase.app.App`, hence the need to patch its prototype and also to pass through the `this` we were called with.

I think ideally Firecrypt would automatically share encryption config among all instances connected to the same host but it's not really worth the trouble to implement at this point.
___
*[src/firecrypt.js, line 90 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItNYF-2Dnw85OaThsX:-LJC256555BHl832v55N:bhx3pmr) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/firecrypt.js#L90)):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

I swear that this used to accept `refOrPath`... Super strange. Regardless, I agree that just accepting a path or `undefined` will be all you need. I made that change and I also added `refFromURL()` event though I can't say I ever used it.
</blockquote></details>

Thanks.  The idea is to be fully API-compatible, so I'm just comparing this file to the docs.
___
*[src/firecrypt.js, line 112 at r4](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LJCRih_47NGKkPmwKAf:-LJCRih_47NGKkPmwKAg:buxjhv6) ([raw file](https://github.com/pkaminski/firecrypt/blob/27121b43934849985fb3bffd023296cdabb28079/src/firecrypt.js#L112)):*
> ```JavaScript
>     this._ensureEncryptionConfigured();
> 
>     if (typeof path !== 'undefined' && typeof path !== 'string') {
> ```

I'm not convinced these argument checks are necessary, since the delegated method will perform them for us anyway.
___
*[src/FireCryptReference.js, line 10 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItR0VeDhoueaTbF16f:-LJC2HcPC3E0bxOcTqWf:bbm8u2i) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/FireCryptReference.js#L10)):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

Done. I also cleaned up similar code in the other classes. I kept the `_interceptQuery()` patching there given the number of methods, but I can change that as well if you'd like.
</blockquote></details>

I don't mind the `intercept` methods, but they should be patching the prototype once, not each individual instance when constructed.
___
*[src/FireCryptReference.js, line 141 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItPPaI597r-E7Azglp:-LJC2eSC1mwml21uzClB:b-ijpr1j) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/FireCryptReference.js#L141)):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

I see what you are saying. You mean that it may not properly wait until the `set()` method is complete. In my testing, it seems to always work, but I do think there is a race condition. I honestly just spent an inordinate amount of time trying to get this to work properly and even tried reverting this to something similar to what you had initially (which proxies the encryption via `set()`), but I was unable to get it to work properly. I honestly have no idea how your initial code ever worked to be honest. If you have an idea of how to do this properly, please let me know.
</blockquote></details>

The initial code worked because `Firebase.push` delegated to `Firebase.set` and used the thennable it returned to patch the ref.  I think you could do it explicitly like this instead now:

```js
const pushedRef = this.child(this._ref.push().key);
let promise;
if (typeof arguments[0] === 'undefined') {
  // Assuming a bare push result should also be thennable; the docs aren't 100% clear.
  promise = Promise.resolve();  
} else {
  promise = pushedRef.set.apply(pushedRef , arguments);
}
pushedRef.then = promise.then;
pushedRef.catch = promise.catch;
if (promise.finally) pushedRef.finally = promise.finally;
return pushedRef;
```

This skips the `decryptRef` call since we're only taking the `key` from the raw pushed ref (which is not encrypted), and passing it straight to `child`, which expects a decrypted path.
___
*[src/FireCryptReference.js, line 160 at r4](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LJCSuH-2-FilRJQiQio:-LJCSuH-2-FilRJQiQip:b613qpl) ([raw file](https://github.com/pkaminski/firecrypt/blob/27121b43934849985fb3bffd023296cdabb28079/src/FireCryptReference.js#L160)):*
> ```JavaScript
> 
>   childrenKeys() {
>     if (!this._ref.childrenKeys) {
> ```

This check will always fail since `_ref` is a raw Firebase ref.  You need to safely check if `firebase-childrenkeys` can be required (and whether `require` is even available for that matter).

The check for `ref.childrenKeys` needs to be up in NodeFire, which is (potentially) layered over FireCrypt.
___
*[src/FireCryptReference.js, line 188 at r4](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LJCTnpNBDVcEr8pddhm:-LJCTnpNBDVcEr8pddhn:bqhkgm) ([raw file](https://github.com/pkaminski/firecrypt/blob/27121b43934849985fb3bffd023296cdabb28079/src/FireCryptReference.js#L188)):*
> ```JavaScript
> 
>   transaction() {
>     const self = this;
> ```

Or just use `=>` to bind instead...


<!-- Sent from Reviewable.io -->

2018-08-12 01:18 UTC, jwngr reviewed
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/6)* status: all files reviewed, 8 unresolved discussions (waiting on @jwngr and @pkaminski)

___
*[src/crypto.js, line 108 at r4](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LJCUgKs3zdjqeYm8MMX:-LJfbHEr47j-rf_WM6GA:b-3p6zr6) ([raw file](https://github.com/pkaminski/firecrypt/blob/27121b43934849985fb3bffd023296cdabb28079/src/crypto.js#L108)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Instead of binding `transform` to the crypto instance at all the call sites it probably makes more sense to bind it here, or even just accept `'encrypt' || 'decrypt'` as the parameter and look it up and bind it.  (The only reason I passed the raw functions originally is because it was convenient.)
</blockquote></details>

Done. Great suggestion.
___
*[src/firecrypt.js, line 18 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItLUQo8gX0dsOO--_7:-LJff6_4En5YMhnaygsk:b15dgzl) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/firecrypt.js#L18)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I'm passing `url` since that's what the `database` method (optionally) [expects](https://firebase.google.com/docs/reference/admin/node/admin.app.App#database), and we need to remain API-compatible.

The `firebase.app.App.prototype` bit is to make Firecrypt compatible with the client SDK.  While `firebase-admin` has a static `admin.database()` method, the client SDK has it as an instance method on `firebase.app.App`, hence the need to patch its prototype and also to pass through the `this` we were called with.

I think ideally Firecrypt would automatically share encryption config among all instances connected to the same host but it's not really worth the trouble to implement at this point.

</blockquote></details>

You're definitely right about the URL. Another feature I apparently have never used.

Both the admin and client SDKs have static [`firebase.database()`](https://firebase.google.com/docs/reference/js/firebase.database#examples) and [`admin.database()`](https://firebase.google.com/docs/reference/admin/node/admin.database#examples) methods as well as instance methods [`firebase.app.App.database()`](https://firebase.google.com/docs/reference/js/firebase.app.App#database) and [`admin.app.App.database()`](https://firebase.google.com/docs/reference/admin/node/admin.app.App#database). To do this properly, we may have to use `Object.defineProperty()` once for the static method and one for the instance method.

Does that sound right to you?
___
*[src/firecrypt.js, line 112 at r4](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LJCRih_47NGKkPmwKAf:-LJfVOmz6uN18uGndvAp:b-3pl4ie) ([raw file](https://github.com/pkaminski/firecrypt/blob/27121b43934849985fb3bffd023296cdabb28079/src/firecrypt.js#L112)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I'm not convinced these argument checks are necessary, since the delegated method will perform them for us anyway.
</blockquote></details>

Yes, but the Firebase SDK leaves a lot to be desired with their error messages. As an example, doing `db.ref({})` results in a `TypeError: pathString.replace is not a function` error in the Firebase SDK. I think this will yield better error messages and it's already written, so I'll keep it around.
___
*[src/FireCryptReference.js, line 10 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItR0VeDhoueaTbF16f:-LJfYyYU8V5CpdNX61yM:b-8pd11f) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/FireCryptReference.js#L10)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I don't mind the `intercept` methods, but they should be patching the prototype once, not each individual instance when constructed.
</blockquote></details>

I decided to just do it properly and define each function individually on the class.
___
*[src/FireCryptReference.js, line 141 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItPPaI597r-E7Azglp:-LJfePkOAwCfRbVE3WZ1:blu4wtm) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/FireCryptReference.js#L141)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

The initial code worked because `Firebase.push` delegated to `Firebase.set` and used the thennable it returned to patch the ref.  I think you could do it explicitly like this instead now:

```js
const pushedRef = this.child(this._ref.push().key);
let promise;
if (typeof arguments[0] === 'undefined') {
  // Assuming a bare push result should also be thennable; the docs aren't 100% clear.
  promise = Promise.resolve();  
} else {
  promise = pushedRef.set.apply(pushedRef , arguments);
}
pushedRef.then = promise.then;
pushedRef.catch = promise.catch;
if (promise.finally) pushedRef.finally = promise.finally;
return pushedRef;
```

This skips the `decryptRef` call since we're only taking the `key` from the raw pushed ref (which is not encrypted), and passing it straight to `child`, which expects a decrypted path.

</blockquote></details>

Thanks for the code. I got it to work with one modification: I needed to bind each promise method to `promise` so it had the proper `this` context. Otherwise it threw a `Promise.prototype.then called on incompatible receiver` error. I tested the latest code and can confirm it is encrypting things properly.
___
*[src/FireCryptReference.js, line 160 at r4](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LJCSuH-2-FilRJQiQio:-LJfelhwDUN52XRY4i8v:b-co2etv) ([raw file](https://github.com/pkaminski/firecrypt/blob/27121b43934849985fb3bffd023296cdabb28079/src/FireCryptReference.js#L160)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

This check will always fail since `_ref` is a raw Firebase ref.  You need to safely check if `firebase-childrenkeys` can be required (and whether `require` is even available for that matter).

The check for `ref.childrenKeys` needs to be up in NodeFire, which is (potentially) layered over FireCrypt.
</blockquote></details>

Will resolve once the ongoing `firebase-childrenkeys` PR gets merged in and released.
___
*[src/FireCryptReference.js, line 188 at r4](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LJCTnpNBDVcEr8pddhm:-LJfZe2z3FPzBmg4R1Xg:b-896fix) ([raw file](https://github.com/pkaminski/firecrypt/blob/27121b43934849985fb3bffd023296cdabb28079/src/FireCryptReference.js#L188)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Or just use `=>` to bind instead...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-08-12 02:41 UTC, pkaminski requested changes
> Reviewed 10 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/6)* status: all files reviewed, 2 unresolved discussions (waiting on @pkaminski)

___
*[src/firecrypt.js, line 18 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItLUQo8gX0dsOO--_7:-LJfz6tVDoUV1tBe_eGQ:bvk0n5a) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/firecrypt.js#L18)):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

You're definitely right about the URL. Another feature I apparently have never used.

Both the admin and client SDKs have static [`firebase.database()`](https://firebase.google.com/docs/reference/js/firebase.database#examples) and [`admin.database()`](https://firebase.google.com/docs/reference/admin/node/admin.database#examples) methods as well as instance methods [`firebase.app.App.database()`](https://firebase.google.com/docs/reference/js/firebase.app.App#database) and [`admin.app.App.database()`](https://firebase.google.com/docs/reference/admin/node/admin.app.App#database). To do this properly, we may have to use `Object.defineProperty()` once for the static method and one for the instance method.

Does that sound right to you?
</blockquote></details>

Bleah, what an unnecessarily complicated API.  Yeah, I think you're right -- gotta override both methods in both SDKs.


<!-- Sent from Reviewable.io -->

2018-08-12 16:07 UTC, jwngr reviewed
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/6)* status: 6 of 14 files reviewed, 2 unresolved discussions (waiting on @pkaminski)

___
*[src/firecrypt.js, line 18 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItLUQo8gX0dsOO--_7:-LJisPGN28VKGHORUFaV:b-i4wc21) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/firecrypt.js#L18)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Bleah, what an unnecessarily complicated API.  Yeah, I think you're right -- gotta override both methods in both SDKs.
</blockquote></details>

The motivation behind the API is that (1) you can have multiple app instances, each with their own auth and even possibly pointing to different projects and (2) 99% of users will only ever have one app, so mind as well make that one available directly off of `admin` / `firebase`. It is a bit overly complex though.

I don't believe any changes need to be made to this library regarding this. I will make sure to properly override both database entry points in any code that uses this library
___
*[src/FireCryptReference.js, line 160 at r4](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LJCSuH-2-FilRJQiQio:-LJisMhm5nTbGpYWdgcQ:b-896fix) ([raw file](https://github.com/pkaminski/firecrypt/blob/27121b43934849985fb3bffd023296cdabb28079/src/FireCryptReference.js#L160)):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

Will resolve once the ongoing `firebase-childrenkeys` PR gets merged in and released.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-08-12 18:24 UTC, pkaminski requested changes
> Reviewed 8 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/6)* status: all files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[src/firecrypt.js, line 18 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItLUQo8gX0dsOO--_7:-LJjNDaz1rx0RaeMrdsL:b-aulf0b) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/firecrypt.js#L18)):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

The motivation behind the API is that (1) you can have multiple app instances, each with their own auth and even possibly pointing to different projects and (2) 99% of users will only ever have one app, so mind as well make that one available directly off of `admin` / `firebase`. It is a bit overly complex though.

I don't believe any changes need to be made to this library regarding this. I will make sure to properly override both database entry points in any code that uses this library
</blockquote></details>

No, the idea is that as soon as you load the `firecrypt` module all the Firebase entrypoints get overridden so you can't accidentally leave encryption uninitialized.  The overrides need to happen here.


<!-- Sent from Reviewable.io -->

2018-08-12 19:02 UTC, jwngr reviewed
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/6)* status: all files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[src/firecrypt.js, line 18 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItLUQo8gX0dsOO--_7:-LJjVA843gce0YJA8fcL:b9aiuco) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/firecrypt.js#L18)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

No, the idea is that as soon as you load the `firecrypt` module all the Firebase entrypoints get overridden so you can't accidentally leave encryption uninitialized.  The overrides need to happen here.
</blockquote></details>

How exactly would that work? Do you want FireCrypt to load the Firebase Admin SDK and do the overrides directly at the top of this file? Currently all we have access to is the provided `db` argument and there is no way to do the overrides from that. I'm happy to do the overrides here, I just don't know how you envision it working.


<!-- Sent from Reviewable.io -->

2018-08-12 19:57 UTC, pkaminski requested changes
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/6)* status: all files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[src/firecrypt.js, line 18 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItLUQo8gX0dsOO--_7:-LJjhRzx3WnDE24g14_D:bblzt0m) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/firecrypt.js#L18)):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

How exactly would that work? Do you want FireCrypt to load the Firebase Admin SDK and do the overrides directly at the top of this file? Currently all we have access to is the provided `db` argument and there is no way to do the overrides from that. I'm happy to do the overrides here, I just don't know how you envision it working.
</blockquote></details>

Just like you said, except it needs to be isomorphic.  So probe for `require`, if it exists then require and patch the admin SDK, otherwise probe for `firebase` and patch that, if neither exists then crash with an error that directs the developer to load the SDK first.


<!-- Sent from Reviewable.io -->

2018-08-27 19:14 UTC, jwngr reviewed
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/6)* status: 6 of 14 files reviewed, 1 unresolved discussion (waiting on @pkaminski and @jwngr)

___
*[src/firecrypt.js, line 18 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItLUQo8gX0dsOO--_7:-LKwmn1l0yE8TAROSCof:bodq5lm) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/firecrypt.js#L18)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Just like you said, except it needs to be isomorphic.  So probe for `require`, if it exists then require and patch the admin SDK, otherwise probe for `firebase` and patch that, if neither exists then crash with an error that directs the developer to load the SDK first.
</blockquote></details>

I'm having trouble getting the app instance properly patched. I initially tried patching the prototype like you suggested, but I was not able to find anything on `fb.app.App` or `fb.app.prototype`. My current attempt mostly works except it results in this error:

```
Error: Encryption for this FireCrypt reference has not been configured yet.
    at FireCrypt._ensureEncryptionConfigured (/Users/jwngr/dev/firecrypt/dist/node/firecrypt.js:791:13)
    at FireCrypt.ref (/Users/jwngr/dev/firecrypt/dist/node/firecrypt.js:863:10)
    at FireCrypt.ref (/Users/jwngr/dev/firecrypt/dist/node/firecrypt.js:869:44)
    at Object.<anonymous> (/Users/jwngr/dev/firecrypt/test.js:75:16)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
```

upon running this:

```
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: `https://${serviceAccount.project_id}.firebaseio.com`,
});

const options = {
  algorithm: 'aes-siv',
  key: '<KEY>',
};

const specification = {
  rules: {
    firecrypt: {
      $wild1: {
        $wild2: {
          '.encrypt': {
            key: '#',
            value: '#',
          },
        },
      },
    },
  },
};

const db = admin.database();
db.configureEncryption(options, specification);
const ref = db.ref('firecrypt');
```

I think I'm going to need your prototype-patching-fu to help me bring this to the finish line...


<!-- Sent from Reviewable.io -->

2018-08-27 21:38 UTC, pkaminski commented
___
*[src/firecrypt.js, line 18 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItLUQo8gX0dsOO--_7:-LKxIg8x6IBiqpc6bwsJ:b-bep5rr) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/firecrypt.js#L18)):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

I'm having trouble getting the app instance properly patched. I initially tried patching the prototype like you suggested, but I was not able to find anything on `fb.app.App` or `fb.app.prototype`. My current attempt mostly works except it results in this error:

```
Error: Encryption for this FireCrypt reference has not been configured yet.
    at FireCrypt._ensureEncryptionConfigured (/Users/jwngr/dev/firecrypt/dist/node/firecrypt.js:791:13)
    at FireCrypt.ref (/Users/jwngr/dev/firecrypt/dist/node/firecrypt.js:863:10)
    at FireCrypt.ref (/Users/jwngr/dev/firecrypt/dist/node/firecrypt.js:869:44)
    at Object.<anonymous> (/Users/jwngr/dev/firecrypt/test.js:75:16)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
```

upon running this:

```
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: `https://${serviceAccount.project_id}.firebaseio.com`,
});

const options = {
  algorithm: 'aes-siv',
  key: '<KEY>',
};

const specification = {
  rules: {
    firecrypt: {
      $wild1: {
        $wild2: {
          '.encrypt': {
            key: '#',
            value: '#',
          },
        },
      },
    },
  },
};

const db = admin.database();
db.configureEncryption(options, specification);
const ref = db.ref('firecrypt');
```

I think I'm going to need your prototype-patching-fu to help me bring this to the finish line...
</blockquote></details>

Can you temporarily commit your test so I can try things out?  I don't think your code is completely correct but it looks like it should work for this simple test...  Thanks.


<!-- Sent from Reviewable.io -->

2018-08-28 06:35 UTC, pkaminski requested changes
While working on the monkeypatching I noticed that Rollup complains about circular module dependencies.  Likely harmless but bad form -- if it's easy to fix by factoring out the cycle, please do so.

> Reviewed 8 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/6#-:-LKz7IKS78in33aeeb2W:b2fw7x6)* status: all files reviewed, 3 unresolved discussions (waiting on @pkaminski and @jwngr)

___
*[package.json, line 30 at r7](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LKz7BUZ8s3r_L-ryD7I:-LKz7BUZ8s3r_L-ryD7J:b-qax6q6) ([raw file](https://github.com/pkaminski/firecrypt/blob/cd708ff4aa77afab73c8f4111a9db9b6f2732923/package.json#L30)):*
> ```JSON
>     "crypto-js": "^3.1.9-1",
>     "cryptojs-extension": "pkaminski/cryptojs-extension",
>     "firebase-admin": "^6.0.0",
> ```

Should leave this to `peerDependencies`, did it sneak in by mistake?
___
*[src/firecrypt.js, line 18 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItLUQo8gX0dsOO--_7:-LKz6SY7E3Bfy0lvpo_z:bdt2m9n) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/firecrypt.js#L18)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Can you temporarily commit your test so I can try things out?  I don't think your code is completely correct but it looks like it should work for this simple test...  Thanks.
</blockquote></details>

This code appears to do the trick, but please double-check the documented assumptions based on your knowledge of the API.  I also wasn't able to easily test it against the client SDK (since the Node test will always probe `require` and take that path) but I believe it should work there as well.

```js
const patchFirebaseDatabaseApi = (fb) => {
  // We want to wrap all instances of the Firebase database() with FireCrypt.  These are always
  // eventually instantiated via an App's database() function, so we'd like to override that.
  // However, we can't get at the App prototype directly so instead we patch initializeApp(),
  // which must be called for an app instance to become available, and patch the App prototype
  // on the first call.  Once the prototype is patched, we can restore the original initializeApp.
  const originalInitializeApp = fb.initializeApp;
  Object.defineProperty(fb, 'initializeApp', {value: function() {
    const app = originalInitializeApp.apply(this, arguments);
    const originalDatabase = app.constructor.prototype.database;
    Object.defineProperty(app.constructor.prototype, 'database', {value: function() {
      // The database() call caches databases by URL and can return the same instance on separate
      // calls.  Ensure that there's a 1-to-1 correspondance between database instances and
      // FireCrypt wrappers by associating a wrapper with its underlying database.
      const db = originalDatabase.apply(this, arguments);
      if (!db.firecrypt) {
        Object.defineProperty(db, 'firecrypt', {value: new FireCrypt(db)});
      }
      return db.firecrypt;
    }});
    Object.defineProperty(fb, 'initializeApp', {value: originalInitializeApp});
    return app;
  }, configurable: true})
}
```
___
*[src/firecrypt.js, line 45 at r7](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LKz72nX8h4-Ayrlt_iA:-LKz72nX8h4-Ayrlt_iB:bleq5a9) ([raw file](https://github.com/pkaminski/firecrypt/blob/cd708ff4aa77afab73c8f4111a9db9b6f2732923/src/firecrypt.js#L45)):*
> ```JavaScript
> import FireCryptReference from './FireCryptReference';
> 
> export default class FireCrypt {
> ```

With the monkey-patching approach we don't need to (and shouldn't) export anything from this module.


<!-- Sent from Reviewable.io -->

2018-09-05 17:48 UTC, jwngr reviewed
I am not aware of a clean way to refactor them out since the Firebase API does allow you to easily grab one object type to another. I also believe they are harmless and don't seem to be affecting bundle size nor usage.

> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/6#-:-LLepwn2-NHdSol8nVfM:b-5nn7t6)* status: 7 of 14 files reviewed, 3 unresolved discussions (waiting on @pkaminski and @jwngr)

___
*[package.json, line 30 at r7](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LKz7BUZ8s3r_L-ryD7I:-LLemHJDCTQdF_hV2GZ7:b-896fix) ([raw file](https://github.com/pkaminski/firecrypt/blob/cd708ff4aa77afab73c8f4111a9db9b6f2732923/package.json#L30)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Should leave this to `peerDependencies`, did it sneak in by mistake?
</blockquote></details>

Done.
___
*[src/firecrypt.js, line 18 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LItLUQo8gX0dsOO--_7:-LLenkn7E95vysoft9-l:bny1cp1) ([raw file](https://github.com/pkaminski/firecrypt/blob/b3427c30f03c266e8ea6e83cee893838447d7c6d/src/firecrypt.js#L18)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

This code appears to do the trick, but please double-check the documented assumptions based on your knowledge of the API.  I also wasn't able to easily test it against the client SDK (since the Node test will always probe `require` and take that path) but I believe it should work there as well.

```js
const patchFirebaseDatabaseApi = (fb) => {
  // We want to wrap all instances of the Firebase database() with FireCrypt.  These are always
  // eventually instantiated via an App's database() function, so we'd like to override that.
  // However, we can't get at the App prototype directly so instead we patch initializeApp(),
  // which must be called for an app instance to become available, and patch the App prototype
  // on the first call.  Once the prototype is patched, we can restore the original initializeApp.
  const originalInitializeApp = fb.initializeApp;
  Object.defineProperty(fb, 'initializeApp', {value: function() {
    const app = originalInitializeApp.apply(this, arguments);
    const originalDatabase = app.constructor.prototype.database;
    Object.defineProperty(app.constructor.prototype, 'database', {value: function() {
      // The database() call caches databases by URL and can return the same instance on separate
      // calls.  Ensure that there's a 1-to-1 correspondance between database instances and
      // FireCrypt wrappers by associating a wrapper with its underlying database.
      const db = originalDatabase.apply(this, arguments);
      if (!db.firecrypt) {
        Object.defineProperty(db, 'firecrypt', {value: new FireCrypt(db)});
      }
      return db.firecrypt;
    }});
    Object.defineProperty(fb, 'initializeApp', {value: originalInitializeApp});
    return app;
  }, configurable: true})
}
```
</blockquote></details>

Looks great to me! I tested it out using all the different ways I know to grab a database instance and it always seemed to be properly patched:

```js
const fs = require('fs');
const path = require('path');
const admin = require('firebase-admin');

const FireCrypt = require('./dist/node/firecrypt');

const app = admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: `https://${serviceAccount.project_id}.firebaseio.com`,
});

const secondaryApp = admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: `https://${serviceAccount.project_id}.firebaseio.com`,
}, 'secondary');

console.log(app.database().constructor.name);  // FireCrypt
console.log(secondaryApp.database().constructor.name);  // FireCrypt
console.log(admin.database().constructor.name);  // FireCrypt
console.log(admin.app().database().constructor.name);  // FireCrypt
console.log(admin.app('secondary').database().constructor.name);  // FireCrypt
console.log(admin.app('[DEFAULT]').database().constructor.name);  // FireCrypt
console.log(app.database().app.database().constructor.name);  // FireCrypt
```

I appreciate your help with that.
___
*[src/firecrypt.js, line 45 at r7](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LKz72nX8h4-Ayrlt_iA:-LLemNbW5Hu-EFiCgKRA:b-896fix) ([raw file](https://github.com/pkaminski/firecrypt/blob/cd708ff4aa77afab73c8f4111a9db9b6f2732923/src/firecrypt.js#L45)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

With the monkey-patching approach we don't need to (and shouldn't) export anything from this module.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-09-05 17:54 UTC, jwngr reviewed
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/6)* status: 5 of 14 files reviewed, 3 unresolved discussions (waiting on @pkaminski)

*[a discussion](https://reviewable.io/reviews/pkaminski/firecrypt/6#-LLerYEj4HvPXAZytls-:-LLerYEj4HvPXAZytls0:b-akxn4f) (no related file):*
Alright, this is ready for another review.

---


<!-- Sent from Reviewable.io -->

2018-09-06 02:26 UTC, pkaminski approved these changes
> Reviewed 2 of 8 files at r8, 9 of 9 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/6)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2018-09-06 09:19 UTC, merged